///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTest2Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("4b61ace8-1c0b-42d0-aa0e-e434e3b434c7")]
    public partial class MyTest2Repository : RepoGenBaseFolder
    {
        static MyTest2Repository instance = new MyTest2Repository();
        MyTest2RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the MyTest2Repository element repository.
        /// </summary>
        [RepositoryFolder("4b61ace8-1c0b-42d0-aa0e-e434e3b434c7")]
        public static MyTest2Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTest2Repository() 
            : base("MyTest2Repository", "/", null, 0, false, "4b61ace8-1c0b-42d0-aa0e-e434e3b434c7", ".\\RepositoryImages\\MyTest2Repository4b61ace8.rximgres")
        {
            _applicationundertest = new MyTest2RepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("4b61ace8-1c0b-42d0-aa0e-e434e3b434c7")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("4321fc42-1529-45e4-8e38-ee330e788188")]
        public virtual MyTest2RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTest2RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("4321fc42-1529-45e4-8e38-ee330e788188")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            MyTest2RepositoryFolders.LoginFolder _login;
            MyTest2RepositoryFolders.LogoutFolder _logout;
            MyTest2RepositoryFolders.AddToCartFolder _addtocart;
            MyTest2RepositoryFolders.CartFolder _cart;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='demowebshop.tricentis.com']", parentFolder, 30000, null, false, "4321fc42-1529-45e4-8e38-ee330e788188", "")
            {
                _login = new MyTest2RepositoryFolders.LoginFolder(this);
                _logout = new MyTest2RepositoryFolders.LogoutFolder(this);
                _addtocart = new MyTest2RepositoryFolders.AddToCartFolder(this);
                _cart = new MyTest2RepositoryFolders.CartFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4321fc42-1529-45e4-8e38-ee330e788188")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4321fc42-1529-45e4-8e38-ee330e788188")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Login folder.
            /// </summary>
            [RepositoryFolder("a1ffd7df-945f-4243-a852-ad266cb05585")]
            public virtual MyTest2RepositoryFolders.LoginFolder Login
            {
                get { return _login; }
            }

            /// <summary>
            /// The Logout folder.
            /// </summary>
            [RepositoryFolder("6f53c7fc-acc7-46dd-9757-d539e65ec90a")]
            public virtual MyTest2RepositoryFolders.LogoutFolder Logout
            {
                get { return _logout; }
            }

            /// <summary>
            /// The AddToCart folder.
            /// </summary>
            [RepositoryFolder("28b55247-aa5f-4d42-8ca3-c8d7492d46f6")]
            public virtual MyTest2RepositoryFolders.AddToCartFolder AddToCart
            {
                get { return _addtocart; }
            }

            /// <summary>
            /// The Cart folder.
            /// </summary>
            [RepositoryFolder("f4aa185c-ea79-4da9-96ba-400c4f0fbf9d")]
            public virtual MyTest2RepositoryFolders.CartFolder Cart
            {
                get { return _cart; }
            }
        }

        /// <summary>
        /// The LoginFolder folder.
        /// </summary>
        [RepositoryFolder("a1ffd7df-945f-4243-a852-ad266cb05585")]
        public partial class LoginFolder : RepoGenBaseFolder
        {
            RepoItemInfo _loginbuttonInfo;
            RepoItemInfo _loginformemailInfo;
            RepoItemInfo _loginformpasswordInfo;
            RepoItemInfo _loginformbuttonInfo;

            /// <summary>
            /// Creates a new Login  folder.
            /// </summary>
            public LoginFolder(RepoGenBaseFolder parentFolder) :
                    base("Login", "", parentFolder, 0, null, false, "a1ffd7df-945f-4243-a852-ad266cb05585", "")
            {
                _loginbuttonInfo = new RepoItemInfo(this, "LoginButton", ".//a[@class='ico-login']", 30000, null, "c167aa00-256b-49c4-8858-4ed1697f4560");
                _loginformemailInfo = new RepoItemInfo(this, "LoginFormEmail", ".//input[#'Email']", 30000, null, "33aa5c7a-9e88-40cf-bed7-9ce307f7f561");
                _loginformpasswordInfo = new RepoItemInfo(this, "LoginFormPassword", ".//input[#'Password']", 30000, null, "48dbe36c-af0d-4cbd-a51c-a8818e84b95a");
                _loginformbuttonInfo = new RepoItemInfo(this, "LoginFormButton", ".//div[@class='buttons']/input[@type='submit']", 30000, null, "12604952-c5b9-4dc7-9e9c-56e895d9a1db");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a1ffd7df-945f-4243-a852-ad266cb05585")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LoginButton item.
            /// </summary>
            [RepositoryItem("c167aa00-256b-49c4-8858-4ed1697f4560")]
            public virtual Ranorex.ATag LoginButton
            {
                get
                {
                    return _loginbuttonInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LoginButton item info.
            /// </summary>
            [RepositoryItemInfo("c167aa00-256b-49c4-8858-4ed1697f4560")]
            public virtual RepoItemInfo LoginButtonInfo
            {
                get
                {
                    return _loginbuttonInfo;
                }
            }

            /// <summary>
            /// The LoginFormEmail item.
            /// </summary>
            [RepositoryItem("33aa5c7a-9e88-40cf-bed7-9ce307f7f561")]
            public virtual Ranorex.InputTag LoginFormEmail
            {
                get
                {
                    return _loginformemailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LoginFormEmail item info.
            /// </summary>
            [RepositoryItemInfo("33aa5c7a-9e88-40cf-bed7-9ce307f7f561")]
            public virtual RepoItemInfo LoginFormEmailInfo
            {
                get
                {
                    return _loginformemailInfo;
                }
            }

            /// <summary>
            /// The LoginFormPassword item.
            /// </summary>
            [RepositoryItem("48dbe36c-af0d-4cbd-a51c-a8818e84b95a")]
            public virtual Ranorex.InputTag LoginFormPassword
            {
                get
                {
                    return _loginformpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LoginFormPassword item info.
            /// </summary>
            [RepositoryItemInfo("48dbe36c-af0d-4cbd-a51c-a8818e84b95a")]
            public virtual RepoItemInfo LoginFormPasswordInfo
            {
                get
                {
                    return _loginformpasswordInfo;
                }
            }

            /// <summary>
            /// The LoginFormButton item.
            /// </summary>
            [RepositoryItem("12604952-c5b9-4dc7-9e9c-56e895d9a1db")]
            public virtual Ranorex.InputTag LoginFormButton
            {
                get
                {
                    return _loginformbuttonInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LoginFormButton item info.
            /// </summary>
            [RepositoryItemInfo("12604952-c5b9-4dc7-9e9c-56e895d9a1db")]
            public virtual RepoItemInfo LoginFormButtonInfo
            {
                get
                {
                    return _loginformbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The LogoutFolder folder.
        /// </summary>
        [RepositoryFolder("6f53c7fc-acc7-46dd-9757-d539e65ec90a")]
        public partial class LogoutFolder : RepoGenBaseFolder
        {
            RepoItemInfo _logoutbuttonInfo;

            /// <summary>
            /// Creates a new Logout  folder.
            /// </summary>
            public LogoutFolder(RepoGenBaseFolder parentFolder) :
                    base("Logout", "", parentFolder, 0, null, false, "6f53c7fc-acc7-46dd-9757-d539e65ec90a", "")
            {
                _logoutbuttonInfo = new RepoItemInfo(this, "LogoutButton", ".//a[@class='ico-logout']", 30000, null, "50ff0ee3-6f2a-47bf-bfbe-b28c552a4f53");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6f53c7fc-acc7-46dd-9757-d539e65ec90a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LogoutButton item.
            /// </summary>
            [RepositoryItem("50ff0ee3-6f2a-47bf-bfbe-b28c552a4f53")]
            public virtual Ranorex.ATag LogoutButton
            {
                get
                {
                    return _logoutbuttonInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LogoutButton item info.
            /// </summary>
            [RepositoryItemInfo("50ff0ee3-6f2a-47bf-bfbe-b28c552a4f53")]
            public virtual RepoItemInfo LogoutButtonInfo
            {
                get
                {
                    return _logoutbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The AddToCartFolder folder.
        /// </summary>
        [RepositoryFolder("28b55247-aa5f-4d42-8ca3-c8d7492d46f6")]
        public partial class AddToCartFolder : RepoGenBaseFolder
        {
            RepoItemInfo _smartphoneaddtocartInfo;
            RepoItemInfo _electronicsInfo;
            RepoItemInfo _cellphonesInfo;
            RepoItemInfo _apparelshoesInfo;
            RepoItemInfo _bluejeansaddInfo;

            /// <summary>
            /// Creates a new AddToCart  folder.
            /// </summary>
            public AddToCartFolder(RepoGenBaseFolder parentFolder) :
                    base("AddToCart", "", parentFolder, 0, null, false, "28b55247-aa5f-4d42-8ca3-c8d7492d46f6", "")
            {
                _smartphoneaddtocartInfo = new RepoItemInfo(this, "SmartphoneAddtoCart", "body/div[4]/div[1]/div[4]/div[2]/div[2]/div[2]/div[3]/div[1]/div/div[2]/div[3]/?/?/input[@type='button']", 30000, null, "1d6faa93-df45-4f1e-8bc1-b73cbb8e03de");
                _electronicsInfo = new RepoItemInfo(this, "Electronics", "body/div[4]/div[1]/div[4]//ul/li[3]/a[@innertext='Electronics        ']", 30000, null, "d95a8b08-c4c0-4462-9c14-44d289b1635d");
                _cellphonesInfo = new RepoItemInfo(this, "CellPhones", "body/div[4]/div[1]/div[4]/div[1]/div[1]/div[2]/ul/li[3]/ul/?/?/a[@innertext='Cell phones        ']", 30000, null, "62a66e9e-70b3-4f60-a22d-702435e138e4");
                _apparelshoesInfo = new RepoItemInfo(this, "ApparelShoes", "body/div[4]/div[1]/div[4]//ul/li[4]/a[@innertext='Apparel & Shoes        ']", 30000, null, "c7c7e853-b316-419b-89f4-7d4cede3b978");
                _bluejeansaddInfo = new RepoItemInfo(this, "BlueJeansAdd", ".//input[@onclick='AjaxCart.addproducttocart_catalog(''/addproducttocart/catalog/36/1/1    '');return false;']", 30000, null, "3409f154-a11f-4f96-a46e-4462aa7878fb");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("28b55247-aa5f-4d42-8ca3-c8d7492d46f6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SmartphoneAddtoCart item.
            /// </summary>
            [RepositoryItem("1d6faa93-df45-4f1e-8bc1-b73cbb8e03de")]
            public virtual Ranorex.InputTag SmartphoneAddtoCart
            {
                get
                {
                    return _smartphoneaddtocartInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SmartphoneAddtoCart item info.
            /// </summary>
            [RepositoryItemInfo("1d6faa93-df45-4f1e-8bc1-b73cbb8e03de")]
            public virtual RepoItemInfo SmartphoneAddtoCartInfo
            {
                get
                {
                    return _smartphoneaddtocartInfo;
                }
            }

            /// <summary>
            /// The Electronics item.
            /// </summary>
            [RepositoryItem("d95a8b08-c4c0-4462-9c14-44d289b1635d")]
            public virtual Ranorex.ATag Electronics
            {
                get
                {
                    return _electronicsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Electronics item info.
            /// </summary>
            [RepositoryItemInfo("d95a8b08-c4c0-4462-9c14-44d289b1635d")]
            public virtual RepoItemInfo ElectronicsInfo
            {
                get
                {
                    return _electronicsInfo;
                }
            }

            /// <summary>
            /// The CellPhones item.
            /// </summary>
            [RepositoryItem("62a66e9e-70b3-4f60-a22d-702435e138e4")]
            public virtual Ranorex.ATag CellPhones
            {
                get
                {
                    return _cellphonesInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The CellPhones item info.
            /// </summary>
            [RepositoryItemInfo("62a66e9e-70b3-4f60-a22d-702435e138e4")]
            public virtual RepoItemInfo CellPhonesInfo
            {
                get
                {
                    return _cellphonesInfo;
                }
            }

            /// <summary>
            /// The ApparelShoes item.
            /// </summary>
            [RepositoryItem("c7c7e853-b316-419b-89f4-7d4cede3b978")]
            public virtual Ranorex.ATag ApparelShoes
            {
                get
                {
                    return _apparelshoesInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ApparelShoes item info.
            /// </summary>
            [RepositoryItemInfo("c7c7e853-b316-419b-89f4-7d4cede3b978")]
            public virtual RepoItemInfo ApparelShoesInfo
            {
                get
                {
                    return _apparelshoesInfo;
                }
            }

            /// <summary>
            /// The BlueJeansAdd item.
            /// </summary>
            [RepositoryItem("3409f154-a11f-4f96-a46e-4462aa7878fb")]
            public virtual Ranorex.InputTag BlueJeansAdd
            {
                get
                {
                    return _bluejeansaddInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The BlueJeansAdd item info.
            /// </summary>
            [RepositoryItemInfo("3409f154-a11f-4f96-a46e-4462aa7878fb")]
            public virtual RepoItemInfo BlueJeansAddInfo
            {
                get
                {
                    return _bluejeansaddInfo;
                }
            }
        }

        /// <summary>
        /// The CartFolder folder.
        /// </summary>
        [RepositoryFolder("f4aa185c-ea79-4da9-96ba-400c4f0fbf9d")]
        public partial class CartFolder : RepoGenBaseFolder
        {
            RepoItemInfo _ordertotalInfo;
            RepoItemInfo _opencartbuttonInfo;

            /// <summary>
            /// Creates a new Cart  folder.
            /// </summary>
            public CartFolder(RepoGenBaseFolder parentFolder) :
                    base("Cart", "", parentFolder, 0, null, false, "f4aa185c-ea79-4da9-96ba-400c4f0fbf9d", "")
            {
                _ordertotalInfo = new RepoItemInfo(this, "OrderTotal", ".//span[@class='product-price order-total']/strong", 30000, null, "c817c279-9558-4ef6-b5e7-3304980f35a6");
                _opencartbuttonInfo = new RepoItemInfo(this, "OpenCartButton", ".//a[@class='ico-cart']", 30000, null, "8556af59-f76b-4e79-8c7d-963025b3eb35");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f4aa185c-ea79-4da9-96ba-400c4f0fbf9d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The OrderTotal item.
            /// </summary>
            [RepositoryItem("c817c279-9558-4ef6-b5e7-3304980f35a6")]
            public virtual Ranorex.StrongTag OrderTotal
            {
                get
                {
                    return _ordertotalInfo.CreateAdapter<Ranorex.StrongTag>(true);
                }
            }

            /// <summary>
            /// The OrderTotal item info.
            /// </summary>
            [RepositoryItemInfo("c817c279-9558-4ef6-b5e7-3304980f35a6")]
            public virtual RepoItemInfo OrderTotalInfo
            {
                get
                {
                    return _ordertotalInfo;
                }
            }

            /// <summary>
            /// The OpenCartButton item.
            /// </summary>
            [RepositoryItem("8556af59-f76b-4e79-8c7d-963025b3eb35")]
            public virtual Ranorex.ATag OpenCartButton
            {
                get
                {
                    return _opencartbuttonInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The OpenCartButton item info.
            /// </summary>
            [RepositoryItemInfo("8556af59-f76b-4e79-8c7d-963025b3eb35")]
            public virtual RepoItemInfo OpenCartButtonInfo
            {
                get
                {
                    return _opencartbuttonInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
