///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Demowebshop
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the DemowebshopRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("3f7a4a6f-7184-4bac-b134-e85ed6b7c268")]
    public partial class DemowebshopRepository : RepoGenBaseFolder
    {
        static DemowebshopRepository instance = new DemowebshopRepository();
        DemowebshopRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        DemowebshopRepositoryFolders.SchakelenTussenTakenAppFolder _schakelentussentaken;
        DemowebshopRepositoryFolders.DemoWebShopLoginGoogleChromeAppFolder _demowebshoplogingooglechrome;
        DemowebshopRepositoryFolders.ExplorerAppFolder _explorer;
        DemowebshopRepositoryFolders.DemoWebShopShoppingCartGoogleChAppFolder _demowebshopshoppingcartgooglech;

        /// <summary>
        /// Gets the singleton class instance representing the DemowebshopRepository element repository.
        /// </summary>
        [RepositoryFolder("3f7a4a6f-7184-4bac-b134-e85ed6b7c268")]
        public static DemowebshopRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public DemowebshopRepository() 
            : base("DemowebshopRepository", "/", null, 0, false, "3f7a4a6f-7184-4bac-b134-e85ed6b7c268", ".\\RepositoryImages\\DemowebshopRepository3f7a4a6f.rximgres")
        {
            _applicationundertest = new DemowebshopRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _schakelentussentaken = new DemowebshopRepositoryFolders.SchakelenTussenTakenAppFolder(this);
            _demowebshoplogingooglechrome = new DemowebshopRepositoryFolders.DemoWebShopLoginGoogleChromeAppFolder(this);
            _explorer = new DemowebshopRepositoryFolders.ExplorerAppFolder(this);
            _demowebshopshoppingcartgooglech = new DemowebshopRepositoryFolders.DemoWebShopShoppingCartGoogleChAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("3f7a4a6f-7184-4bac-b134-e85ed6b7c268")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("42068ff3-7bb1-47ce-bdf7-38cb1f6efcfa")]
        public virtual DemowebshopRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The SchakelenTussenTaken folder.
        /// </summary>
        [RepositoryFolder("618d3f13-2ad7-4951-a2e3-7e9bd0badc2b")]
        public virtual DemowebshopRepositoryFolders.SchakelenTussenTakenAppFolder SchakelenTussenTaken
        {
            get { return _schakelentussentaken; }
        }

        /// <summary>
        /// The DemoWebShopLoginGoogleChrome folder.
        /// </summary>
        [RepositoryFolder("7eac6dfd-d751-4ea9-b4f9-37931cbf2c84")]
        public virtual DemowebshopRepositoryFolders.DemoWebShopLoginGoogleChromeAppFolder DemoWebShopLoginGoogleChrome
        {
            get { return _demowebshoplogingooglechrome; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("dad31388-7c8a-40fa-914e-b40366e92f82")]
        public virtual DemowebshopRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The DemoWebShopShoppingCartGoogleCh folder.
        /// </summary>
        [RepositoryFolder("73123d86-2954-4a17-a276-c1eecd4231a8")]
        public virtual DemowebshopRepositoryFolders.DemoWebShopShoppingCartGoogleChAppFolder DemoWebShopShoppingCartGoogleCh
        {
            get { return _demowebshopshoppingcartgooglech; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class DemowebshopRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("42068ff3-7bb1-47ce-bdf7-38cb1f6efcfa")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            DemowebshopRepositoryFolders.HttpDemowebshopTricentisComCartFolder _httpdemowebshoptricentiscomcart;
            RepoItemInfo _loginInfo;
            RepoItemInfo _submitInfo;
            RepoItemInfo _tricentisdemowebshopInfo;
            RepoItemInfo _somebodytagInfo;
            RepoItemInfo _emailInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _logoutInfo;
            RepoItemInfo _removefromcartInfo;
            RepoItemInfo _shoppingcartInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='demowebshop.tricentis.com']", parentFolder, 30000, null, false, "42068ff3-7bb1-47ce-bdf7-38cb1f6efcfa", "")
            {
                _httpdemowebshoptricentiscomcart = new DemowebshopRepositoryFolders.HttpDemowebshopTricentisComCartFolder(this);
                _loginInfo = new RepoItemInfo(this, "LogIn", "body/div[4]/div[1]/div[1]/div[2]/?/?/ul/?/?/a[@innertext='Log in']", 30000, null, "6e34a755-a833-49e1-b34b-3601fe4aed0e");
                _submitInfo = new RepoItemInfo(this, "Submit", "body/div[4]/div[1]/div[4]/div[2]/div/div[2]/div[1]//form[@action='http://demowebshop.tricentis.com/login']/div[5]/input[@type='submit']", 30000, null, "18beb61a-3cd9-49a0-b3d7-1e26a1060879");
                _tricentisdemowebshopInfo = new RepoItemInfo(this, "TricentisDemoWebShop", "body/div[4]/div[1]/div[1]/div[1]/?/?/img[@title='']", 30000, null, "1db8f720-39cf-4fb5-b7f7-3cb546a48a0e");
                _somebodytagInfo = new RepoItemInfo(this, "SomeBodyTag", "body", 30000, null, "3b942789-3d25-4c93-9051-7877bdfcd77a");
                _emailInfo = new RepoItemInfo(this, "Email", ".//input[#'Email']", 30000, null, "70fb6e45-a9f4-4006-be80-8487c7a66c5e");
                _passwordInfo = new RepoItemInfo(this, "Password", ".//input[#'Password']", 30000, null, "324e970a-c73d-435d-92d4-2e56b2711bf9");
                _logoutInfo = new RepoItemInfo(this, "LogOut", "body/div[4]/div[1]/div[1]/div[2]/?/?/ul/?/?/a[@innertext='Log out']", 30000, null, "098115bb-6c38-4f8e-a03c-9e75b87ae220");
                _removefromcartInfo = new RepoItemInfo(this, "RemoveFromCart", "body/div[4]/div[1]/div[4]//form[@action='http://demowebshop.tricentis.com/cart']/table/tbody/tr[1]/td[1]", 30000, null, "2e0eeaaf-5abf-47b5-883d-b398a992a7fc");
                _shoppingcartInfo = new RepoItemInfo(this, "ShoppingCart", ".//li[#'topcartlink']/?/?/span[@innertext='Shopping cart']", 30000, null, "9c8ed9bd-3ad1-41d7-a05c-d44ff70a5720");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("42068ff3-7bb1-47ce-bdf7-38cb1f6efcfa")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("42068ff3-7bb1-47ce-bdf7-38cb1f6efcfa")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LogIn item.
            /// </summary>
            [RepositoryItem("6e34a755-a833-49e1-b34b-3601fe4aed0e")]
            public virtual Ranorex.ATag LogIn
            {
                get
                {
                    return _loginInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LogIn item info.
            /// </summary>
            [RepositoryItemInfo("6e34a755-a833-49e1-b34b-3601fe4aed0e")]
            public virtual RepoItemInfo LogInInfo
            {
                get
                {
                    return _loginInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("18beb61a-3cd9-49a0-b3d7-1e26a1060879")]
            public virtual Ranorex.InputTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("18beb61a-3cd9-49a0-b3d7-1e26a1060879")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The TricentisDemoWebShop item.
            /// </summary>
            [RepositoryItem("1db8f720-39cf-4fb5-b7f7-3cb546a48a0e")]
            public virtual Ranorex.ImgTag TricentisDemoWebShop
            {
                get
                {
                    return _tricentisdemowebshopInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The TricentisDemoWebShop item info.
            /// </summary>
            [RepositoryItemInfo("1db8f720-39cf-4fb5-b7f7-3cb546a48a0e")]
            public virtual RepoItemInfo TricentisDemoWebShopInfo
            {
                get
                {
                    return _tricentisdemowebshopInfo;
                }
            }

            /// <summary>
            /// The SomeBodyTag item.
            /// </summary>
            [RepositoryItem("3b942789-3d25-4c93-9051-7877bdfcd77a")]
            public virtual Ranorex.BodyTag SomeBodyTag
            {
                get
                {
                    return _somebodytagInfo.CreateAdapter<Ranorex.BodyTag>(true);
                }
            }

            /// <summary>
            /// The SomeBodyTag item info.
            /// </summary>
            [RepositoryItemInfo("3b942789-3d25-4c93-9051-7877bdfcd77a")]
            public virtual RepoItemInfo SomeBodyTagInfo
            {
                get
                {
                    return _somebodytagInfo;
                }
            }

            /// <summary>
            /// The Email item.
            /// </summary>
            [RepositoryItem("70fb6e45-a9f4-4006-be80-8487c7a66c5e")]
            public virtual Ranorex.InputTag Email
            {
                get
                {
                    return _emailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Email item info.
            /// </summary>
            [RepositoryItemInfo("70fb6e45-a9f4-4006-be80-8487c7a66c5e")]
            public virtual RepoItemInfo EmailInfo
            {
                get
                {
                    return _emailInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("324e970a-c73d-435d-92d4-2e56b2711bf9")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("324e970a-c73d-435d-92d4-2e56b2711bf9")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The LogOut item.
            /// </summary>
            [RepositoryItem("098115bb-6c38-4f8e-a03c-9e75b87ae220")]
            public virtual Ranorex.ATag LogOut
            {
                get
                {
                    return _logoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LogOut item info.
            /// </summary>
            [RepositoryItemInfo("098115bb-6c38-4f8e-a03c-9e75b87ae220")]
            public virtual RepoItemInfo LogOutInfo
            {
                get
                {
                    return _logoutInfo;
                }
            }

            /// <summary>
            /// The RemoveFromCart item.
            /// </summary>
            [RepositoryItem("2e0eeaaf-5abf-47b5-883d-b398a992a7fc")]
            public virtual Ranorex.TdTag RemoveFromCart
            {
                get
                {
                    return _removefromcartInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The RemoveFromCart item info.
            /// </summary>
            [RepositoryItemInfo("2e0eeaaf-5abf-47b5-883d-b398a992a7fc")]
            public virtual RepoItemInfo RemoveFromCartInfo
            {
                get
                {
                    return _removefromcartInfo;
                }
            }

            /// <summary>
            /// The ShoppingCart item.
            /// </summary>
            [RepositoryItem("9c8ed9bd-3ad1-41d7-a05c-d44ff70a5720")]
            public virtual Ranorex.SpanTag ShoppingCart
            {
                get
                {
                    return _shoppingcartInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ShoppingCart item info.
            /// </summary>
            [RepositoryItemInfo("9c8ed9bd-3ad1-41d7-a05c-d44ff70a5720")]
            public virtual RepoItemInfo ShoppingCartInfo
            {
                get
                {
                    return _shoppingcartInfo;
                }
            }

            /// <summary>
            /// The HttpDemowebshopTricentisComCart folder.
            /// </summary>
            [RepositoryFolder("206896c2-5013-44e9-bbeb-e4bfbeabce2f")]
            public virtual DemowebshopRepositoryFolders.HttpDemowebshopTricentisComCartFolder HttpDemowebshopTricentisComCart
            {
                get { return _httpdemowebshoptricentiscomcart; }
            }
        }

        /// <summary>
        /// The HttpDemowebshopTricentisComCartFolder folder.
        /// </summary>
        [RepositoryFolder("206896c2-5013-44e9-bbeb-e4bfbeabce2f")]
        public partial class HttpDemowebshopTricentisComCartFolder : RepoGenBaseFolder
        {
            RepoItemInfo _updatecartInfo;
            RepoItemInfo _removefromcart1Info;
            RepoItemInfo _removefromcart2Info;

            /// <summary>
            /// Creates a new HttpDemowebshopTricentisComCart  folder.
            /// </summary>
            public HttpDemowebshopTricentisComCartFolder(RepoGenBaseFolder parentFolder) :
                    base("HttpDemowebshopTricentisComCart", "body/div[4]/div[1]/div[4]//form[@action='http://demowebshop.tricentis.com/cart']", parentFolder, 30000, null, false, "206896c2-5013-44e9-bbeb-e4bfbeabce2f", "")
            {
                _updatecartInfo = new RepoItemInfo(this, "Updatecart", "div[1]/?/?/input[@name='updatecart']", 30000, null, "b222fb55-be7d-44d8-8d64-ccf3d6896654");
                _removefromcart1Info = new RepoItemInfo(this, "Removefromcart1", "table/tbody/tr[1]/td[1]/input[@name='removefromcart']", 30000, null, "62af6723-6aa0-4a51-8985-39e1c3889338");
                _removefromcart2Info = new RepoItemInfo(this, "Removefromcart2", "table/tbody/tr[2]/td[1]/input[@name='removefromcart']", 30000, null, "6d12a458-7484-4028-afc5-79cde43c8c60");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("206896c2-5013-44e9-bbeb-e4bfbeabce2f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("206896c2-5013-44e9-bbeb-e4bfbeabce2f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Updatecart item.
            /// </summary>
            [RepositoryItem("b222fb55-be7d-44d8-8d64-ccf3d6896654")]
            public virtual Ranorex.InputTag Updatecart
            {
                get
                {
                    return _updatecartInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Updatecart item info.
            /// </summary>
            [RepositoryItemInfo("b222fb55-be7d-44d8-8d64-ccf3d6896654")]
            public virtual RepoItemInfo UpdatecartInfo
            {
                get
                {
                    return _updatecartInfo;
                }
            }

            /// <summary>
            /// The Removefromcart1 item.
            /// </summary>
            [RepositoryItem("62af6723-6aa0-4a51-8985-39e1c3889338")]
            public virtual Ranorex.InputTag Removefromcart1
            {
                get
                {
                    return _removefromcart1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Removefromcart1 item info.
            /// </summary>
            [RepositoryItemInfo("62af6723-6aa0-4a51-8985-39e1c3889338")]
            public virtual RepoItemInfo Removefromcart1Info
            {
                get
                {
                    return _removefromcart1Info;
                }
            }

            /// <summary>
            /// The Removefromcart2 item.
            /// </summary>
            [RepositoryItem("6d12a458-7484-4028-afc5-79cde43c8c60")]
            public virtual Ranorex.InputTag Removefromcart2
            {
                get
                {
                    return _removefromcart2Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Removefromcart2 item info.
            /// </summary>
            [RepositoryItemInfo("6d12a458-7484-4028-afc5-79cde43c8c60")]
            public virtual RepoItemInfo Removefromcart2Info
            {
                get
                {
                    return _removefromcart2Info;
                }
            }
        }

        /// <summary>
        /// The SchakelenTussenTakenAppFolder folder.
        /// </summary>
        [RepositoryFolder("618d3f13-2ad7-4951-a2e3-7e9bd0badc2b")]
        public partial class SchakelenTussenTakenAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new SchakelenTussenTaken  folder.
            /// </summary>
            public SchakelenTussenTakenAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SchakelenTussenTaken", "/form[@title='Schakelen tussen taken']", parentFolder, 30000, null, true, "618d3f13-2ad7-4951-a2e3-7e9bd0badc2b", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("618d3f13-2ad7-4951-a2e3-7e9bd0badc2b")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("618d3f13-2ad7-4951-a2e3-7e9bd0badc2b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The DemoWebShopLoginGoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("7eac6dfd-d751-4ea9-b4f9-37931cbf2c84")]
        public partial class DemoWebShopLoginGoogleChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _paneInfo;
            RepoItemInfo _pane1Info;

            /// <summary>
            /// Creates a new DemoWebShopLoginGoogleChrome  folder.
            /// </summary>
            public DemoWebShopLoginGoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DemoWebShopLoginGoogleChrome", "/form[@title>'Demo Web Shop. Login - Google']", parentFolder, 30000, null, true, "7eac6dfd-d751-4ea9-b4f9-37931cbf2c84", "")
            {
                _paneInfo = new RepoItemInfo(this, "Pane", "container[@accessiblename>'Demo Web Shop. Login - Google']/container/container[2]/container[1]", 30000, null, "09fbe63d-fc74-4be1-ad78-d42e7408de0e");
                _pane1Info = new RepoItemInfo(this, "Pane1", "container[@accessiblename>'Tweakers - Wij stellen technologie']/container/container[2]/container[1]", 30000, null, "9caa0e30-c7fb-46e6-b4c2-8100816aedb8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7eac6dfd-d751-4ea9-b4f9-37931cbf2c84")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7eac6dfd-d751-4ea9-b4f9-37931cbf2c84")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Pane item.
            /// </summary>
            [RepositoryItem("09fbe63d-fc74-4be1-ad78-d42e7408de0e")]
            public virtual Ranorex.Container Pane
            {
                get
                {
                    return _paneInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Pane item info.
            /// </summary>
            [RepositoryItemInfo("09fbe63d-fc74-4be1-ad78-d42e7408de0e")]
            public virtual RepoItemInfo PaneInfo
            {
                get
                {
                    return _paneInfo;
                }
            }

            /// <summary>
            /// The Pane1 item.
            /// </summary>
            [RepositoryItem("9caa0e30-c7fb-46e6-b4c2-8100816aedb8")]
            public virtual Ranorex.Container Pane1
            {
                get
                {
                    return _pane1Info.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Pane1 item info.
            /// </summary>
            [RepositoryItemInfo("9caa0e30-c7fb-46e6-b4c2-8100816aedb8")]
            public virtual RepoItemInfo Pane1Info
            {
                get
                {
                    return _pane1Info;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("dad31388-7c8a-40fa-914e-b40366e92f82")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _googlechrome1actiefvensterInfo;
            RepoItemInfo _ranorexstudio1actiefvensterInfo;
            RepoItemInfo _googlechromeInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "dad31388-7c8a-40fa-914e-b40366e92f82", "")
            {
                _googlechrome1actiefvensterInfo = new RepoItemInfo(this, "GoogleChrome1ActiefVenster", "container[@controlid='40965']//toolbar[@accessiblename='Actieve toepassingen']/button[@accessiblename>'Google Chrome - 1 actief']", 30000, null, "3cfa381e-ccb4-4f23-aeda-23649cce355b");
                _ranorexstudio1actiefvensterInfo = new RepoItemInfo(this, "RanorexStudio1ActiefVenster", "container[@controlid='40965']//toolbar[@accessiblename='Actieve toepassingen']/button[@accessiblename>'RanorexStudio - 1 actief']", 30000, null, "8815b01d-752b-4a64-935e-bd75754b375b");
                _googlechromeInfo = new RepoItemInfo(this, "GoogleChrome", "container[@controlid='40965']//toolbar[@accessiblename='Actieve toepassingen']/button[@accessiblename='Google Chrome']", 30000, null, "c0751787-7b59-48a0-bffa-f0fc77686f4a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("dad31388-7c8a-40fa-914e-b40366e92f82")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("dad31388-7c8a-40fa-914e-b40366e92f82")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The GoogleChrome1ActiefVenster item.
            /// </summary>
            [RepositoryItem("3cfa381e-ccb4-4f23-aeda-23649cce355b")]
            public virtual Ranorex.Button GoogleChrome1ActiefVenster
            {
                get
                {
                    return _googlechrome1actiefvensterInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The GoogleChrome1ActiefVenster item info.
            /// </summary>
            [RepositoryItemInfo("3cfa381e-ccb4-4f23-aeda-23649cce355b")]
            public virtual RepoItemInfo GoogleChrome1ActiefVensterInfo
            {
                get
                {
                    return _googlechrome1actiefvensterInfo;
                }
            }

            /// <summary>
            /// The RanorexStudio1ActiefVenster item.
            /// </summary>
            [RepositoryItem("8815b01d-752b-4a64-935e-bd75754b375b")]
            public virtual Ranorex.Button RanorexStudio1ActiefVenster
            {
                get
                {
                    return _ranorexstudio1actiefvensterInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The RanorexStudio1ActiefVenster item info.
            /// </summary>
            [RepositoryItemInfo("8815b01d-752b-4a64-935e-bd75754b375b")]
            public virtual RepoItemInfo RanorexStudio1ActiefVensterInfo
            {
                get
                {
                    return _ranorexstudio1actiefvensterInfo;
                }
            }

            /// <summary>
            /// The GoogleChrome item.
            /// </summary>
            [RepositoryItem("c0751787-7b59-48a0-bffa-f0fc77686f4a")]
            public virtual Ranorex.Button GoogleChrome
            {
                get
                {
                    return _googlechromeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The GoogleChrome item info.
            /// </summary>
            [RepositoryItemInfo("c0751787-7b59-48a0-bffa-f0fc77686f4a")]
            public virtual RepoItemInfo GoogleChromeInfo
            {
                get
                {
                    return _googlechromeInfo;
                }
            }
        }

        /// <summary>
        /// The DemoWebShopShoppingCartGoogleChAppFolder folder.
        /// </summary>
        [RepositoryFolder("73123d86-2954-4a17-a276-c1eecd4231a8")]
        public partial class DemoWebShopShoppingCartGoogleChAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _paneInfo;

            /// <summary>
            /// Creates a new DemoWebShopShoppingCartGoogleCh  folder.
            /// </summary>
            public DemoWebShopShoppingCartGoogleChAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DemoWebShopShoppingCartGoogleCh", "/form[@title>'Demo Web Shop. Shopping Cart']", parentFolder, 30000, null, true, "73123d86-2954-4a17-a276-c1eecd4231a8", "")
            {
                _paneInfo = new RepoItemInfo(this, "Pane", "container[@accessiblename>'Demo Web Shop. Shopping Cart']/container[@accessiblename='Google Chrome']/container[2]/container[1]/container[@accessiblerole='Pane']/container[1]/container[2]", 30000, null, "9dac2707-0895-42fc-8070-36ccf204546f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("73123d86-2954-4a17-a276-c1eecd4231a8")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("73123d86-2954-4a17-a276-c1eecd4231a8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Pane item.
            /// </summary>
            [RepositoryItem("9dac2707-0895-42fc-8070-36ccf204546f")]
            public virtual Ranorex.Container Pane
            {
                get
                {
                    return _paneInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Pane item info.
            /// </summary>
            [RepositoryItemInfo("9dac2707-0895-42fc-8070-36ccf204546f")]
            public virtual RepoItemInfo PaneInfo
            {
                get
                {
                    return _paneInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
