///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Demowebshop.Steps
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The checkCartContent recording.
    /// </summary>
    [TestModule("1f08fbb5-d554-423b-b7c2-2a0290ddfe75", ModuleType.Recording, 1)]
    public partial class checkCartContent : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Demowebshop.DemowebshopRepository repository.
        /// </summary>
        public static global::Demowebshop.DemowebshopRepository repo = global::Demowebshop.DemowebshopRepository.Instance;

        static checkCartContent instance = new checkCartContent();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public checkCartContent()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static checkCartContent Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ShoppingCart' at 58;3.", repo.ApplicationUnderTest.ShoppingCartInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.ShoppingCart.Click("58;3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ApplicationUnderTest.RemoveFromCart'.", repo.ApplicationUnderTest.RemoveFromCartInfo, new RecordItemIndex(1));
            Validate.Exists(repo.ApplicationUnderTest.RemoveFromCartInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
