///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Demowebshop.Steps
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ClearCart recording.
    /// </summary>
    [TestModule("35558628-7aca-4683-ab88-57db9a5a128d", ModuleType.Recording, 1)]
    public partial class ClearCart : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Demowebshop.DemowebshopRepository repository.
        /// </summary>
        public static global::Demowebshop.DemowebshopRepository repo = global::Demowebshop.DemowebshopRepository.Instance;

        static ClearCart instance = new ClearCart();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ClearCart()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ClearCart Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ShoppingCart' at 37;7.", repo.ApplicationUnderTest.ShoppingCartInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.ShoppingCart.Click("37;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.HttpDemowebshopTricentisComCart.Removefromcart1' at 7;4.", repo.ApplicationUnderTest.HttpDemowebshopTricentisComCart.Removefromcart1Info, new RecordItemIndex(1));
            repo.ApplicationUnderTest.HttpDemowebshopTricentisComCart.Removefromcart1.Click("7;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.HttpDemowebshopTricentisComCart.Removefromcart2' at 8;6.", repo.ApplicationUnderTest.HttpDemowebshopTricentisComCart.Removefromcart2Info, new RecordItemIndex(2));
            repo.ApplicationUnderTest.HttpDemowebshopTricentisComCart.Removefromcart2.Click("8;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.HttpDemowebshopTricentisComCart.Updatecart' at 64;7.", repo.ApplicationUnderTest.HttpDemowebshopTricentisComCart.UpdatecartInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.HttpDemowebshopTricentisComCart.Updatecart.Click("64;7");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
